development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: beginner
  database: mydb

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5

cucumber:
  <<: *TEST